#!/bin/bash

hours=()
count=0

usage () {
	cat <<- EOF

	Usage: ${0##*/} DIR_NAME

	EOF
}


if [[ ! -d "$1" ]]; then
	usage >&2
	exit 1
fi


for i in {0..23}; do
	hours[i]=0
done

for i in $(stat -c %y $1/* | cut -c 12-13); do
	valid_index=${i#0}
	(( hours[valid_index]++ ))
	(( count++ ))
done

printf "Hour\tFiles\tHour\tFiles\n"
printf "====\t=====\t====\t=====\n"

for i in {0..11}; do
	j=$((i + 12))
	printf "%02d\t%d\t%02d\t%d\n" $i ${hours[i]} $j ${hours[j]}
done

printf "\nTotal files = %d\n" $count
