#!/bin/bash

DELAY=3

while true; do
	clear
	echo -ne "$(cat prompt_text)"
	read R
	if [[ $R =~ ^[0-3]$ ]]; then
		(( R == 0 )) && break
		(( R == 1 )) && (echo "Uptime ($HOSTNAME)"; uptime; sleep $DELAY; continue)
		(( R == 2 )) && (echo "Disk usage ($USER)"; df -h; sleep $DELAY; continue)
		
		if (( R == 3 )); then
			if (( $(id -u) == 0 )); then
				echo "Disk utilization (All users)" 
				du -sh /home/*
			else
				echo "Disk utilization ($USER)" 
				du -sh $HOME
			fi
			sleep $DELAY
			continue
		fi
	else
		echo "Selection is not valid" >&2
		sleep $DELAY
	fi
done

echo "Bye!"
