#!/bin/bash

read -p "Please enter value > "

declare -l lower_value="${REPLY:-"Default Value"}"
declare -u upper_value="${REPLY:-"Default Value"}"

cat <<- EOF

Upper: $upper_value or ${REPLY^^} or ${REPLY^}
Lower: $lower_value or ${REPLY,,} or ${REPLY,}

EOF
