#!/bin/bash

read -p "Please enter value > "

declare -l lower_value="${REPLY:-"Default Value"}"
declare -u upper_value="${REPLY:-"Default Value"}"

cat <<- EOF
Upper is $upper_value
Lower is $lower_value
EOF
