#!/bin/bash

echo -en "\e[92mPlease enter integer here >> \e[0m"
read INT

if [[ $INT =~ ^-?[0-9]+$ ]]; then
	if ((INT == 0)); then
		echo "Integer is zero"
		exit 0
	fi
	if ((INT < 0)); then
		echo "Integer less then zero"
	fi
	if ((INT > 0)); then
		echo "Integer more then zero"
	fi
	if (( ((INT % 2)) == 0 )); then
		echo "Integer is even"
	else
		echo "Integer is odd"
	fi
else
	echo "Current Integer is not a integer or not exists"
fi
