#!/bin/bash

echo -en "\e[92mPlease enter integer here >> \e[0m"
read

if [[ $REPLY =~ ^-?[0-9]+$ ]]; then
	if ((REPLY == 0)); then
		echo "$REPLY is zero"
		exit 0
	fi
	if ((REPLY < 0)); then
		echo "$REPLY less then zero"
	fi
	if ((REPLY > 0)); then
		echo "$REPLY more then zero"
	fi
	if (( ((REPLY % 2)) == 0 )); then
		echo "$REPLY is even"
	else
		echo "$REPLY is odd"
	fi
else
	echo "Current value is not a integer"
fi
