#!/bin/bash

for i; do
	if [[ -r "$i" ]]; then
		max_substring=
		max_len=0
		for j in $(strings "$i"); do
			len="${#j}"
			if (( len > max_len )); then
				max_word="$j"
				max_len="$len"
			fi
		done
		echo "In $i max word is '$max_word' ($max_len)"
	fi
done
